# Generated by Django 5.1.3 on 2024-11-14 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_original',
            field=models.ImageField(blank=True, null=True, upload_to='products/images', verbose_name='Оригинальное изображение'),
        ),
    ]
